<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'order.index' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order']], [], []],
    'order.tobasket' => [['idProduct'], ['_controller' => 'App\\Controller\\OrderController::addToBasket'], [], [['variable', '/', '[^/]++', 'idProduct'], ['text', '/order/addToBasket']], [], []],
    'order.delete' => [['idProduct'], ['_controller' => 'App\\Controller\\OrderController::deletefomBasket'], [], [['variable', '/', '[^/]++', 'idProduct'], ['text', '/order/basket/delete']], [], []],
    'order.basket' => [[], ['_controller' => 'App\\Controller\\OrderController::basket'], [], [['text', '/order/basket']], [], []],
    'pages.home' => [[], ['_controller' => 'App\\Controller\\PageController::home'], [], [['text', '/']], [], []],
    'pages.about' => [[], ['_controller' => 'App\\Controller\\PageController::about'], [], [['text', '/about']], [], []],
    'products.index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/products']], [], []],
    'products.edit' => [['idProduct'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['variable', '/', '[^/]++', 'idProduct'], ['text', '/products/edit']], [], []],
    'products.update' => [['idProduct'], ['_controller' => 'App\\Controller\\ProductController::update'], [], [['variable', '/', '[^/]++', 'idProduct'], ['text', '/products/update']], [], []],
    'products.add' => [[], ['_controller' => 'App\\Controller\\ProductController::add'], [], [['text', '/products/add']], [], []],
    'products.save' => [[], ['_controller' => 'App\\Controller\\ProductController::save'], [], [['text', '/products/save']], [], []],
    'products.delete' => [['idProduct'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'idProduct'], ['text', '/products/delete']], [], []],
    'products.show' => [['idProduct'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'idProduct'], ['text', '/products/show']], [], []],
];
